module.exports = {
  _id: "68d128b9517e670141128a12",
  googlePlayEmail: "GOOGLE PLAY EMAIL",
  stripePublishableKey: "YOUR_STRIPE_PUBLISHABLE_KEY",
  stripeSecretKey: "YOUR_STRIPE_SECRET_KEY",
  razorPayId: "rzp_live_ShPkaC43DiPCJ4",
  razorSecretKey: "rzJLujIoNRtgeWM51I5endt3",
  privacyPolicyLink:
    "https://www.privacypolicygenerator.info/live.php?token=EXAMPLE_TOKEN",
  privacyPolicyText: "PRIVACY POLICY TEXT",
  googlePlaySwitch: true,
  stripeSwitch: true,
  razorPaySwitch: true,
  isAppActive: false,
  paymentGateway: [],
  currency: "$",
  createdAt: "2022-12-02T10:36:30.324Z",
  updatedAt: "2024-06-22T12:57:11.505Z",
  __v: 0,
  googlePlayKey: "GOOGLE PLAY KEY",
  isIptvAPI: true,
  privateKey: {
    type: "service_account",
    project_id: "YOUR_PROJECT_ID",
    private_key_id: "YOUR_PRIVATE_KEY_ID",
    private_key: "YOUR_PRIVATE_KEY",
    client_email: "YOUR_CLIENT_EMAIL",
    client_id: "YOUR_CLIENT_ID",
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://oauth2.googleapis.com/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: "YOUR_CLIENT_X509_CERT_URL",
    universe_domain: "googleapis.com",
  },
  flutterWaveId: "YOUR_FLUTTER_WAVE_ID",
  flutterWaveSwitch: true,
  durationOfShorts: 2000,
  resendApiKey: "YOUR_RESEND_API_KEY",
  storage: {
    local: true,
    awsS3: false,
    digitalOcean: false,
  },
  awsAccessKey: "YOUR_AWS_ACCESS_KEY",
  awsBucketName: "YOUR_AWS_BUCKET_NAME",
  awsEndpoint: "https://s3.us-east-1.amazonaws.com",
  awsHostname: "https://s3.us-east-1.amazonaws.com",
  awsRegion: "us-east-1",
  awsSecretKey: "YOUR_AWS_SECRET_KEY",
  cloudFrontDomain: "",
  doAccessKey: "YOUR_DO_ACCESS_KEY",
  doBucketName: "YOUR_DO_BUCKET_NAME",
  doEndpoint: "YOUR_DO_ENDPOINT",
  doHostname: "YOUR_DO_HOSTNAME",
  doRegion: "YOUR_DO_REGION",
  doSecretKey: "YOUR_DO_SECRET_KEY",
  termConditionLink:
    "https://www.privacypolicygenerator.info/live.php?token=EXAMPLE_TOKEN",
};
